# WAREHOUSE_MAPPING = {
#     "Bergen Logistics NJ299": "BLNJ",
#     "Bergen Logistics PA1055": "BLPA",
# }

WarehouseMapping: 
  Bergen Logistics NJ299: BLNJ
  Bergen Logistics PA1055: BLPA

base_location: data